# Generated by Django 4.2.26 on 2026-05-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalsection",
            name="color",
            field=models.CharField(
                default="#3b82f6", help_text="Hex color code", max_length=7
            ),
        ),
    ]
