# Generated by Django 4.2.26 on 2026-05-14 22:06

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('submissions', '0002_journalsection_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlesubmission',
            name='keywords',
        ),
        migrations.AlterField(
            model_name='articlesubmission',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='submissions.journalsection'),
        ),
        migrations.AddField(
            model_name='articlesubmission',
            name='keywords',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='الكلمات المفتاحية'),
        ),
    ]
