# Generated by Django 4.2.26 on 2026-05-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_remove_articlesubmission_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coauthor',
            name='email',
        ),
        migrations.AddField(
            model_name='articlesubmission',
            name='corresponding_author_email',
            field=models.EmailField(blank=True, help_text='البريد الإلكتروني للمؤلف المسؤول عن المراسلات', max_length=254),
        ),
    ]
