# Generated by Django 4.2.26 on 2026-05-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_remove_coauthor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('under_initial_check', 'قيد الفحص الأولي'), ('under_review', 'قيد المراجعة'), ('revision_required', 'يتطلب تعديلات'), ('accepted_awaiting_payment', 'مقبول – في انتظار الدفع'), ('payment_processing', 'جاري معالجة الدفع'), ('paid', 'تم الدفع'), ('published', 'منشور'), ('rejected', 'مرفوض'), ('expired', 'منتهي الصلاحية'), ('withdrawn', 'مسحوبة')], default='draft', max_length=30),
        ),
    ]
