# Generated by Django 5.2.15 on 2026-06-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_articlesubmission_is_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalsection',
            options={'ordering': ['order', 'name']},
        ),
        migrations.RemoveField(
            model_name='journalsection',
            name='color',
        ),
        migrations.AddField(
            model_name='journalsection',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='المسلسل'),
        ),
    ]
