# Generated by Django 4.2.26 on 2026-04-17 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                (
                    "quarter",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Jan–Mar"),
                            (2, "Apr–Jun"),
                            (3, "Jul–Sep"),
                            (4, "Oct–Dec"),
                        ]
                    ),
                ),
                ("is_current", models.BooleanField(default=False)),
                ("published_at", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-volume__number", "-number"],
            },
        ),
        migrations.CreateModel(
            name="Volume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(unique=True)),
                ("year", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="PublishedArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("abstract", models.TextField()),
                ("keywords", models.CharField(max_length=500)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("views_count", models.PositiveIntegerField(default=0)),
                (
                    "issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="publishing.issue",
                    ),
                ),
                (
                    "manuscript_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="submissions.manuscriptfile",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="submissions.journalsection",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published",
                        to="submissions.articlesubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.AddField(
            model_name="issue",
            name="volume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="publishing.volume",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="issue",
            unique_together={("volume", "number")},
        ),
    ]
