# Generated by Django 4.2.26 on 2026-05-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0002_publishedarticle_slug_and_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='quarter',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Jan-Mar'), (2, 'Apr-Jun'), (3, 'Jul-Sep'), (4, 'Oct-Dec')]),
        ),
    ]
