# Generated by Django 4.2.11 on 2026-06-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0003_alter_issue_quarter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='quarter',
            field=models.PositiveSmallIntegerField(choices=[(1, 'يناير'), (2, 'مارس'), (3, 'مايو'), (4, 'يوليو'), (5, 'سبتمبر'), (6, 'نوفمبر')]),
        ),
    ]
