# Generated by Django 5.2.15 on 2026-06-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0004_alter_issue_quarter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-published_at', '-volume__number', '-number']},
        ),
    ]
