# Generated by Django 4.2.26 on 2026-04-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "journal_name",
                    models.CharField(default="Scientific Journal", max_length=255),
                ),
                ("journal_desc", models.TextField(blank=True)),
                (
                    "apc_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("payment_deadline_days", models.PositiveSmallIntegerField(default=30)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_address", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
